# Generated by Django 5.2.1 on 2025-06-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('compostion', models.TextField(default='')),
                ('proadapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('BL', 'blueberryicecream'), ('AT', 'avocadotoast'), ('BB', 'bibimbap'), ('BI', 'biriyani'), ('BP', 'blueberrypancake'), ('BY', 'blueberrypie'), ('CC', 'cheesecake'), ('CL', 'chocolatecake'), ('CR', 'croissant'), ('DO', 'donuts'), ('FH', 'fish'), ('FC', 'friedchicken'), ('FY', 'fruityogertbowl'), ('FB', 'fudgeybrownie'), ('GB', 'gimbap'), ('GS', 'GrilledSkewers'), ('KK', 'kaju'), ('LO', 'laddos'), ('MB', 'meatburger'), ('PI', 'pizza'), ('PO', 'poori'), ('RA', 'ramen'), ('RI', 'ribs'), ('SA', 'salad'), ('JK', 'samgyeopsal'), ('SM', 'samosa'), ('SF', 'shrimpfry'), ('ST', 'steak'), ('TP', 'tomatopasta'), ('WF', 'waffles')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
