# Generated by Django 5.2.1 on 2025-06-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('proadapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('IC', 'INDIAN CUISINE'), ('KC', 'KOREAN CUISINE'), ('JK', 'JAPANESE CUISINE'), ('AC', 'AMERICAN CUISINE'), ('DR', 'DRINKS')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
