# Generated by Django 5.2.1 on 2025-06-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'INDIAN CUISINE'), ('KC', 'KOREAN CUISINE'), ('JK', 'JAPANESE CUISINE'), ('AC', 'AMERICAN CUISINE'), ('DE', 'DESSERTS'), ('DR', 'DRINKS')], max_length=2),
        ),
    ]
