# Generated by Django 5.2.1 on 2025-06-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'INDIAN CUISINE'), ('KC', 'KOREAN CUISINE'), ('JC', 'JAPANESE CUISINE'), ('AC', 'AMERICAN CUISINE'), ('DE', 'DESSERTS'), ('DR', 'DRINKS')], max_length=2),
        ),
    ]
